# Generated by Django 4.2.5 on 2023-11-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_table",
            name="num_people_field",
            field=models.IntegerField(
                choices=[(1, "1 People"), (2, "2 People"), (3, "3 People")], default=1
            ),
        ),
    ]
